# Generated by Django 5.2.8 on 2025-12-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Product/image/')),
                ('sku', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=40)),
                ('oldprice', models.IntegerField(max_length=40)),
                ('category', models.CharField()),
                ('size', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
